const prisma = require('../db');

const TOKEN = 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI5ZjZkNWU4OGM5ZDE5YWM3NWM4NjU4ZmQwNzFmNTNhOCIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiOWY2ZDVlODhjOWQxOWFjNzVjODY1OGZkMDcxZjUzYTgiLCJpYXQiOjE3Nzc4MzkwMTgsImV4cCI6MTc4NTYxNTAxOH0.hAGpz8tDqK_kqHdkDsPtLRa8Vxy2gSliAVHGxaMz2Q6Ty6u5QfTIupEQMbD7n3LfuaOTFCyArLS5HPgHmmcReKVPFSvPDi0ZBsevgv3S7T7cKW3X3dipgjxaH51XgspsyAiNkfx7gTNDAB-f58Skx9aA1eP2Fhopw3bp8IL21bEgX-atkRmHPJ9kIzksjZkPsi3BNO4xjjm-khThJb2_9dsJqSMh9PALiWQK_HP1K_4GpssDI9-5640vJBXIOQ_vHl6vMuradDXM_Y5xjmzRK5fxeZkhXg-f3SuJky2wcfeg9VYM3_49i54yuQuyKSNdx79RVPbgvUUD-3y2oQpwW9P2y6FyST68Gut5vH1fQhTihswULl3npuYwr-h9B_EXfvrtR7h7qx3ekyhbq35KFq0DWSbKvb6b7NV79zrM1tm2r470toyPRiLGCFKhSjuM8nI5acy0LE354zfkezp6_-rizLE2-6RPhJ4_p6UJKtQNntTYWpU5ZZuo8HBwjmLxAD7s-1XVWYJaI4vN5q9_lXsqrEqRVM7q2OJ6NbdZ6nUekK-PYT_YbwhiK3ilM_5RG8VOuuLTnSek7Gfwiu0Z-m7KHWavn5BmfEjdlbcFGn-KKD42phdIz5pJg4yufCEuP4YqvxLjwgA9iQebUsg_5VLkBfrWPCUtug-u7hLM8ks';
const ACCOUNT_ID = '2d3f28ac-dede-437b-9a7c-a27571e4185b';

async function run() {
  try {
    const s = await prisma.systemSettings.findFirst();
    const data = {
      metaApiToken: TOKEN,
      metaApiAccountId: ACCOUNT_ID
    };

    if (s) {
      await prisma.systemSettings.update({ where: { id: s.id }, data });
      console.log('✅ Base de dados atualizada com o Token real.');
    } else {
      await prisma.systemSettings.create({ data });
      console.log('✅ Base de dados criada com o Token real.');
    }
  } catch (e) {
    console.error('❌ Erro:', e.message);
  } finally {
    await prisma.$disconnect();
    process.exit(0);
  }
}

run();
